#!/usr/bin/env bash
# homebrew-formula.sh — print the Homebrew formula for one release, from its
# version and checksums.txt. The tap repository is wktorbert/homebrew-tap;
# users run: brew install wktorbert/tap/sthin
#
# Usage: scripts/homebrew-formula.sh <version> <checksums.txt> > Formula/sthin.rb
set -euo pipefail
version="${1:?version}"; sums="${2:?checksums.txt}"
repo="https://github.com/wktorbert/sthin"
sha() { grep " sthin_${version}_$1.tar.gz\$" "$sums" | awk '{print $1}'; }
for t in darwin_arm64 darwin_amd64 linux_amd64 linux_arm64; do
  [ -n "$(sha $t)" ] || { echo "missing checksum for $t" >&2; exit 1; }
done
cat <<RB
# typed: false
# frozen_string_literal: true

# Generated by scripts/homebrew-formula.sh for sthin v${version}. Do not edit by hand.
class Sthin < Formula
  desc "Boot iOS simulators and Android emulators already slimmed, from one terminal list"
  homepage "${repo}"
  version "${version}"
  license "MIT"

  on_macos do
    on_arm do
      url "${repo}/releases/download/v${version}/sthin_${version}_darwin_arm64.tar.gz"
      sha256 "$(sha darwin_arm64)"
    end
    on_intel do
      url "${repo}/releases/download/v${version}/sthin_${version}_darwin_amd64.tar.gz"
      sha256 "$(sha darwin_amd64)"
    end
  end

  on_linux do
    on_arm do
      url "${repo}/releases/download/v${version}/sthin_${version}_linux_arm64.tar.gz"
      sha256 "$(sha linux_arm64)"
    end
    on_intel do
      url "${repo}/releases/download/v${version}/sthin_${version}_linux_amd64.tar.gz"
      sha256 "$(sha linux_amd64)"
    end
  end

  def install
    bin.install "sthin"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/sthin version")
  end
end
RB
