#!/usr/bin/env bash
# homebrew-formula.sh — print the Homebrew formula for one release, from its
# version and checksums.txt. The tap repository is wktorbert/homebrew-tap;
# users run: brew install wktorbert/tap/sthin
#
# Usage: scripts/homebrew-formula.sh <version> <checksums.txt> > Formula/sthin.rb
set -euo pipefail
version="${1:?version}"; sums="${2:?checksums.txt}"
repo="https://github.com/wktorbert/sthin"
sha() { grep " sthin_${version}_$1.tar.gz\$" "$sums" | awk '{print $1}'; }
# Bottle checksums, by Homebrew tag (see bottle_tag in release-cli.sh).
bsha() { grep " sthin-${version}.$1.bottle.tar.gz\$" "$sums" | awk '{print $1}'; }
for t in darwin_arm64 darwin_amd64 linux_amd64 linux_arm64; do
  [ -n "$(sha $t)" ] || { echo "missing checksum for $t" >&2; exit 1; }
done
for t in arm64_sonoma sonoma x86_64_linux arm64_linux; do
  [ -n "$(bsha $t)" ] || { echo "missing bottle checksum for $t" >&2; exit 1; }
done
cat <<RB
# typed: false
# frozen_string_literal: true

# Generated by scripts/homebrew-formula.sh for sthin v${version}. Do not edit by hand.
class Sthin < Formula
  desc "Boot iOS simulators and Android emulators already slimmed, from one terminal list"
  homepage "${repo}"
  version "${version}"
  license "MIT"

  # Prebuilt bottles. With a matching bottle Homebrew pours it and skips its
  # build-from-source checks, so no Xcode Command Line Tools (macOS) or gcc
  # (Linux) are needed. The macOS tags name the oldest macOS each bottle is
  # for; newer releases pour them too. The url/sha256 blocks below stay as the
  # --build-from-source path and for platforms without a bottle.
  bottle do
    root_url "${repo}/releases/download/v${version}"
    sha256 cellar: :any_skip_relocation, arm64_sonoma: "$(bsha arm64_sonoma)"
    sha256 cellar: :any_skip_relocation, sonoma:       "$(bsha sonoma)"
    sha256 cellar: :any_skip_relocation, arm64_linux:  "$(bsha arm64_linux)"
    sha256 cellar: :any_skip_relocation, x86_64_linux: "$(bsha x86_64_linux)"
  end

  on_macos do
    on_arm do
      url "${repo}/releases/download/v${version}/sthin_${version}_darwin_arm64.tar.gz"
      sha256 "$(sha darwin_arm64)"
    end
    on_intel do
      url "${repo}/releases/download/v${version}/sthin_${version}_darwin_amd64.tar.gz"
      sha256 "$(sha darwin_amd64)"
    end
  end

  on_linux do
    on_arm do
      url "${repo}/releases/download/v${version}/sthin_${version}_linux_arm64.tar.gz"
      sha256 "$(sha linux_arm64)"
    end
    on_intel do
      url "${repo}/releases/download/v${version}/sthin_${version}_linux_amd64.tar.gz"
      sha256 "$(sha linux_amd64)"
    end
  end

  def install
    bin.install "sthin"
    generate_completions_from_executable(bin/"sthin", "completion")
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/sthin version")
  end
end
RB
